Modify messages

diff --git a/DEV-gitSpy/gitSpyInit b/DEV-gitSpy/gitSpyInit
--- a/DEV-gitSpy/gitSpyInit
+++ b/DEV-gitSpy/gitSpyInit
@@ -5,19 +5,21 @@ function createFile {
     touch $1
     cat $2 >> $1
     chmod +xr $1
+    echo "$3 added ʕ•ᴥ•ʔ"
+  else
+    echo "$3 could not be added because it already exists"
   fi
 }
 
 # Add gitSpy/* to .gitignore if it doesn't exist
-if g! grep "gitSpy/*" .gitignore
+if ! grep "gitSpy/*" .gitignore
  then
   echo "gitSpy/*" >> .gitignore
 else
   echo "already added to .gitignore"
 fi
 
-createFile ./.git/hooks/post-rewrite ./gitSpy/scripts/gitspy
-createFile ./.git/hooks/post-commit ./gitSpy/scripts/gitspy
-createFile /usr/local/bin/spyupdate ./gitSpy/scripts/spyupdate
-
-echo "GitSpy hooks added and spyUpdate executable added ʕ•ᴥ•ʔ"
+# Add git hooks and bash script
+createFile ./.git/hooks/post-rewrite ./gitSpy/scripts/gitspy "post-rewrite hook"
+createFile ./.git/hooks/post-commit ./gitSpy/scripts/gitspy "post-commit hook"
+createFile /usr/local/bin/spyupdate ./gitSpy/scripts/spyupdate "spyupdate bash script"
